### ISSUE TITLE
KJR compatible with Breaking Ground? 

### ISSUE THREAD

**Issue by carlilek** [net-lisias-ksp/Kerbal-Joint-Reinforcement#10]
Before I buy the expansion, just checking if KJR is compatible with it. I think half the stuff I've built would spontaneously explode without it... thanks for the mod!

**Comment by Lisias** [comment]
Hi, @carlilek !

I expect the same issues it had in the past with Infernal Robotics, and the same fixes: adding the new Serenity's modules into the Exception List.

However… With KSO-RO's fork, and the on-going-effort on really improving KJR on the KJR/Next by meirumeiru, I'm unsure if this fork still worths the effort of being updated.

I'm not telling you I don't want to do it, I just don't want to spend efforts on something that doesn't worth it anymore.

From a user's point of view, my fork is still relevant? If yes, why? I will consider user's opinions on the matter, be assured.

**Comment by carlilek** [comment]
Hi Lisias, TBH, your fork was the first and only one I've tried. And it worked so well (and I was so happy that my massive munbase wasn't exploding itself any more) that I haven't investigated other options.

**Comment by Lisias** [comment]
I will make a deal with you, @carlilek :

You try the KJR/next thing, and let me know if you have any problems *or* if there's something on KJR/L that you wanted to use and the Next version doesn't have it.

That happening, you ping me here so I will update this and keep it on the loop for some more time while I work with meirumeiru to have the thing fixed/updated/whatever.

Sounds good?

**Comment by carlilek** [comment]
Sure! I'm sure it'll be just fine.

On Jun 1, 2019, at 7:35 PM, Lisias <notifications@github.com<mailto:notifications@github.com>> wrote:


I will make a deal with you, @carlilek<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_carlilek&d=DwMCaQ&c=LU6cRtx0xgB8s29tIz9Olw&r=3a_g5QJW_GZDNmyas1hSrUpqpVKOfUtMndCtaA4OSBM&m=WX-Fq2kzBIlc216sozTWhHZaPH4l6WyC-_W1XXwWydk&s=Q_Q2UNtkFtPjuDl5oUu7WsAy2mktYkLFPpSgtRzdDqE&e=> :

You try the KJR/next thing, and let me know if you have any problems or if there's something on KJR/L that you wanted to use and the Next version doesn't have it.

That happening, you ping me here so I will update this and keep it on the loop for some more time while I work with meirumeiru to have the thing fixed/updated/whatever.

Sounds good?

**Comment by carlilek** [comment]
Hmm. Well, on first try, my munbase shook itself to pieces with the KJR/next. I put KRJ/L back, and it worked fine. Checked the config files, they're pretty much identical. Perhaps I installed it wrong. I will try again.

I run a completely vanilla config as far as KJR goes, and the only other plugin I use is KAC. Otherwise, it's just 1.7.1 (from Steam) with the Making History expansion on MacOS.

On Jun 1, 2019, at 7:36 PM, Carlile, Ken <carlilek@janelia.hhmi.org<mailto:carlilek@janelia.hhmi.org>> wrote:

Sure! I'm sure it'll be just fine.

On Jun 1, 2019, at 7:35 PM, Lisias <notifications@github.com<mailto:notifications@github.com>> wrote:


I will make a deal with you, @carlilek<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_carlilek&d=DwMCaQ&c=LU6cRtx0xgB8s29tIz9Olw&r=3a_g5QJW_GZDNmyas1hSrUpqpVKOfUtMndCtaA4OSBM&m=WX-Fq2kzBIlc216sozTWhHZaPH4l6WyC-_W1XXwWydk&s=Q_Q2UNtkFtPjuDl5oUu7WsAy2mktYkLFPpSgtRzdDqE&e=> :

You try the KJR/next thing, and let me know if you have any problems or if there's something on KJR/L that you wanted to use and the Next version doesn't have it.

That happening, you ping me here so I will update this and keep it on the loop for some more time while I work with meirumeiru to have the thing fixed/updated/whatever.

Sounds good?

**Comment by carlilek** [comment]
Yup, I installed it wrong. Got too clever and tried to use the one directly off of the github repo rather than having a compiled version... all good. Thanks for pointing me in the right direction!

On Jun 1, 2019, at 8:15 PM, Ken Carlile <carlilek@janelia.hhmi.org<mailto:carlilek@janelia.hhmi.org>> wrote:

Hmm. Well, on first try, my munbase shook itself to pieces with the KJR/next. I put KRJ/L back, and it worked fine. Checked the config files, they're pretty much identical. Perhaps I installed it wrong. I will try again.

I run a completely vanilla config as far as KJR goes, and the only other plugin I use is KAC. Otherwise, it's just 1.7.1 (from Steam) with the Making History expansion on MacOS.

On Jun 1, 2019, at 7:36 PM, Carlile, Ken <carlilek@janelia.hhmi.org<mailto:carlilek@janelia.hhmi.org>> wrote:

Sure! I'm sure it'll be just fine.

On Jun 1, 2019, at 7:35 PM, Lisias <notifications@github.com<mailto:notifications@github.com>> wrote:


I will make a deal with you, @carlilek<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_carlilek&d=DwMCaQ&c=LU6cRtx0xgB8s29tIz9Olw&r=3a_g5QJW_GZDNmyas1hSrUpqpVKOfUtMndCtaA4OSBM&m=WX-Fq2kzBIlc216sozTWhHZaPH4l6WyC-_W1XXwWydk&s=Q_Q2UNtkFtPjuDl5oUu7WsAy2mktYkLFPpSgtRzdDqE&e=> :

You try the KJR/next thing, and let me know if you have any problems or if there's something on KJR/L that you wanted to use and the Next version doesn't have it.

That happening, you ping me here so I will update this and keep it on the loop for some more time while I work with meirumeiru to have the thing fixed/updated/whatever.

Sounds good?

**Comment by Lisias** [comment]
Deal! I will update KJR/L this Sunday. :)

Thanks for your care.

**Comment by carlilek** [comment]
No need, if I wasn't clear in my last update, I got KJR/Next working. Thanks again!

On Jun 1, 2019, at 9:10 PM, Lisias <notifications@github.com<mailto:notifications@github.com>> wrote:


Deal! I will update KJR/L this Sunday. :)

Thanks for your care.

**Comment by Lisias** [comment]
So KJR/Next works, and I can leave this dormant for some more time as it appears. :)

Thanks for caring! Happy Strutting!

(closing this as solved)
