### ISSUE TITLE
DStaal has some problems with his Vessel, probable (my) KJR misbehaviour?

### ISSUE THREAD

**Issue by Lisias** [net-lisias-ksp/Kerbal-Joint-Reinforcement#3]
Problem: Decoupler are saggy (TT-70).

Reproduced **wihout** any KJR, but worked as expected with. 

Mod List:
* SSPXe
* Near Future Spacecraft
* Better Science Labs
* Pathfinder
* Surface Lights
* Koose
*  Universal Storage II
    + needs KIS
    + needs KAS
* KOS 

Data to analyse:
* Logs:
   + [KSP1.log](https://github.com/net-lisias-ksp/Kerbal-Joint-Reinforcement/files/2608948/KSP1.log)
   + [Player 1.log](https://github.com/net-lisias-ksp/Kerbal-Joint-Reinforcement/files/2608949/Player.1.log)
* Craft: 
   + [Skylab.craft.zip](https://github.com/net-lisias-ksp/Kerbal-Joint-Reinforcement/files/2608946/Skylab.craft.zip)
   + (hey! **CHECK YO STAGIN!!!** :) )

Infos:
* https://forum.kerbalspaceprogram.com/index.php?/topic/50911-13-kerbal-joint-reinforcement-v333-72417/&do=findComment&comment=3490390
* https://forum.kerbalspaceprogram.com/index.php?/topic/50911-13-kerbal-joint-reinforcement-v333-72417/&do=findComment&comment=3490911
* https://forum.kerbalspaceprogram.com/index.php?/topic/50911-13-kerbal-joint-reinforcement-v333-72417/&do=findComment&comment=3491711
* https://forum.kerbalspaceprogram.com/index.php?/topic/50911-13-kerbal-joint-reinforcement-v333-72417/&do=findComment&comment=3491711

**Comment by Lisias** [comment]
Currently, by best guess is the config.xml in the wrong place, absent or with a syntax error somewhere.

**Comment by Lisias** [comment]
To be tested by the customer:

```
less "/Applications/Games/Kerbal Space Program//PluginData/KerbalJointReinforcement/config.xml"
```

**Comment by Gordon-Dry** [comment]
So this "adecoupler" thing is not a thing anymore?

**Comment by Lisias** [comment]
> So this "adecoupler" thing is not a thing anymore?

this? https://github.com/net-lisias-ksp/Kerbal-Joint-Reinforcement/issues/2

I didn't had time to check it. I need to cook a dedicated vessel to test that "commented out" modules. On a blind test (just "fixed" everything and fire up my production KSP) nothing broke - what's a good thing, but now I need some time to a proper, piece by piece, reproduceable, test run - on the Science Way.

And now, it's time to give TweakScale a care, so I will do it later.

**Comment by Lisias** [comment]
BOM is not a problem. :)  Every file on KSP has it.

Welcome to the wonderful work of CSharp "Standards". :) 

![screen shot 2018-11-24 at 18 03 48](https://user-images.githubusercontent.com/64334/48972551-dc8be280-f013-11e8-86f9-81884658ffae.png)

**Comment by DanStaal** [comment]
Folder structure.  (Note that I've disabled this version of KJR, and reverted in this output.  I compress folders to disable mods.)

[KSP_out.txt](https://github.com/net-lisias-ksp/Kerbal-Joint-Reinforcement/files/2636307/KSP_out.txt)

**Comment by Lisias** [comment]
I detected no config.xml on that listing. So, whatever KJR are you running, it's config-less and so, deactivated.

note to myself: write something on the Log file when reading with success (or failure) the config.xml

**Comment by Lisias** [comment]
@DanStaal  I found the problematic code.

It's a defective hardware on a vital component on the building chain located between my keyboard and my chair.

Working on the problem.

**Comment by Lisias** [comment]
Problem solved, fixed and a new release released "that works for me" :P is available here:

https://github.com/net-lisias-ksp/Kerbal-Joint-Reinforcement/releases/tag/RELEASE%2F3.4.0.1

**Comment by Lisias** [comment]
And this, my friends, is why airplanes crashes and KSP borks. :D 

This incredibly convoluted sequence of events is what was prevented me to detect two obvious and simple problems: a minor error on the Logging initialization and a mistake on the naming of the file `config.xml` on the code. :) 

First things first, follows the scenario as it was presented to me:

* @DanStaal 's KSP stalled (pun not intended) and refused to work with KJR (mine or not).
* Every single attempt to diagnose the problem failed because his Logs are **clean** of KJR related events, while mine was behaving ok.
* After a dump of his directory tree and contents, it was discovered that:
   * "My" KJR has the `config.xml`on the right place, but that thing was not working.
   * The previous KJRs releases (mine or not) was not working due the `config.xml`being not in the older place!

Well… If "my" `config.xml`was in the right place, why in hell "my" KJR wasn't working? A failure on loading the file would trigger an ERROR log! And it was - but on the "wrong" time. :P 

And depending of the version of the KJR he used, the thing could be still locked to 1.3.1 or 1.4.x versions of KSP, a situation in which KJR **silently** shutdowns itself.

DanStall is no fool. He would mentioned an ERROR entry on the log. So the logic explanation is he using a "locked down" KSP version that silently shutdown itself on every Awake and Start events when testing until the Flight scenario, while on "mine" he gave up sooner (as ERRORs are logged on the default logging level, only the informative and warnings logs were being suppressed).

But that doesn't explained the behaviour of the 3.4 series of mine. That damned thing was working fine here, God damnit, I would not had released that thing if it was not!!!

Then Critter79606 hinted that the ZIP file was released without a `.version` file. Hummm… This implies a problem on my automation scripts.

And then @Gordon-Dry , in another thread, had filed a report about a misbehaviour of another add-one I'm (not) maintaining :P, but that ended up being he merging unholy DLLs into sacred packages :D . And then the situation kicked me in the head as a piano would do by falling from the 13th floor!

(damn, boy! Even when you miss the spot, you end up hitting something!! :D )

1. I had a problem on my automation script: I had messed up the DLLs, what I tested wasn't what I delivered!
2. KJR **does not** loads the `config.xml`until the Flight Scene. In the mean time, the logging level is on the Default from KSPe.
3. KJR just sets up the looging level after reading `config.xml`, and just reads the `config.xml` on the Flight Scene, and not before.
3. A lot of messages that I was expecting from "my" KJR wasn't happening due this: the debug option is only activated after reading the `config.xml`, but the `config.xml`was not being found - so the default logging level was too low (mainly due a mishap on KSPe, those default was too low). So "my" KJR was running, but silently - and everybody wrongly concluded it was not working. :D 
4. That problem with KSPe was not exactly a problem - I intentionally shut it's mouth to prevent flooding on the LOG. And since every add-on to the moment initialized the logging on the awake on the Main Menu, Loading or at least Space Center, this was never a problem before.
5. I made a dumb mistake on the 3.4 series on the file naming. But that thing was working on my installments because…. I didn't cleaned properly my building environment, and my script was deploying a older DLL to my testing installments, and another to the Deliverables folder! I was testing something, and deploying another!
6. And, well, DanStall messed up with his installment in a way that he ended up without a single working KJR - as the one that works was killing itself due the KSP version, another was borking due the absence of the `config.xml`on the old place, and mine was borking due a dumb mistake on the file naming and was not reaching a `config.xml` in the right place. :P 

And that's is. A somewhat long sequence of mistakes make by many people that together and on the right order, drove everybody on a closed cycle of self-reference and collective brain farting. :P 

Well… I'm closing this. I have some aircrafts to crash on KSP. :P

**Comment by Lisias** [comment]
Just a follow up, to make things clear. **EVERYBODY** has a brain fart now and then - it was one of mine that started this, right?

What makes a Software great is not the absence of errors - this is not possible with our human condition. What makes a Software great is our disposition on hunting and fixing errors.

To do so, we need to only to accept our human condition, but to embrace it. We **will** commit mistakes, and ideally we must document it and show others so they can learnt too.

The best teachers I had in my life weren't the ones that never err - but the ones that erred a lot, and then told me about every mistake they remember, so I can commit new ones instead of repeating theirs. :D
